name: Test Dependency Updates
on:
  push:
    branches:
      - 'renovate/*'

jobs:
  gtoken:
    runs-on: ubuntu-latest
    steps:
      - name: Install gotestsum
        run: |
          wget https://github.com/gotestyourself/gotestsum/releases/download/v1.7.0/gotestsum_1.7.0_linux_amd64.tar.gz
          tar -xzf gotestsum_1.7.0_linux_amd64.tar.gz
          chmod +x gotestsum
          mkdir -p $HOME/.local/bin
          mv ./gotestsum $HOME/.local/bin
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - name: Run build
        run: |
          go generate ./...
          go build ./...
        working-directory: ./cmd/gtoken
      - name: Run vet & lint
        run: |
          go vet ./...
        working-directory: ./cmd/gtoken
      - name: Unit tests
        run: |
          gotestsum --format testname --junitfile gtoken.xml
        working-directory: ./cmd/gtoken
      
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v2
        if: always() # always run even if the previous step fails
        with:
          report_paths: ./cmd/gtoken/gtoken.xml
          check_name: "gtoken Unit Tests"
  gtoken-webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Install gotestsum
        run: |
          wget https://github.com/gotestyourself/gotestsum/releases/download/v1.7.0/gotestsum_1.7.0_linux_amd64.tar.gz
          tar -xzf gotestsum_1.7.0_linux_amd64.tar.gz
          chmod +x gotestsum
          mkdir -p $HOME/.local/bin
          mv ./gotestsum $HOME/.local/bin
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - name: Run build
        run: |
          go generate ./...
          go build ./...
        working-directory: ./cmd/gtoken-webhook
      - name: Run vet & lint
        run: |
          go vet ./...
        working-directory: ./cmd/gtoken-webhook
      - name: Unit tests
        run: |
          gotestsum --format testname --junitfile gtoken-webhook.xml
        working-directory: ./cmd/gtoken-webhook
      
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v2
        if: always() # always run even if the previous step fails
        with:
          report_paths: ./cmd/gtoken-webhook/gtoken-webhook.xml
          check_name: "gtoken-webhook Unit Tests"